version: 0.2

env:
  parameter-store:
    DB_URL: "/dev/database/connection_string"

phases:
  install:
    commands:
      - echo "Instalando el cliente de PostgreSQL..."
      - yum update -y
      - sudo amazon-linux-extras enable postgresql15
      - yum install postgresql -y

  build:
    commands:
      - echo "Executing pg_isready to check if db is healthy"
      - pg_isready -d $DB_URL
